language: node_js
node_js: "node"
script:
  - git status
  - git checkout ./test
  - npm test
cache:
  directories:
    - node_modules
notifications:
  webhooks:  https://9b7fc5d62196.ngrok.io/webhook/travis
